### ISSUE TITLE
CNN feature

### ISSUE THREAD

**Issue by pp1016** [vztu/BVQA_Benchmark#1]
I saw the pertained ResNet-50/VGG-19 are used as a baseline CNN feature extractor but the results shown in Table V shows that they are very effective. Did you re-train it on other datasets or it just the fixed pertained model from imagenet?Thanks!

**Comment by vztu** [comment]
We just used the pre-trained model as the feature extractor (on patches) and applied SVM as the regressor head.

**Comment by pp1016** [comment]
> We just used the pre-trained model as the feature extractor (on patches) and applied SVM as the regressor head.

Thanks, any thought of why it behaves even better than other specifically designed model?

**Comment by vztu** [comment]
I can only say that CNN features transfer well to BVQA tasks

**Comment by ChairManMeow-SY** [comment]
> I can only say that CNN features transfer well to BVQA tasks

Then why in the ReadMe.md, it is saied "evaluator is not applicable for deep learning method"?
