### ISSUE TITLE
A plead for the implenmentation of EPooling method

### ISSUE THREAD

**Issue by 2279209430** [vztu/BVQA_Benchmark#2]
Dear Dr. Tu,

    Sorry to be a bother.
    Thanks for your work in VQA! I am very interested in your work "EPooling". Could you please share me with the codes of your mentioned VQA pooling methods in "A Comparative Evaluation Of Temporal Pooling Methods For Blind Video Quality Assessment" ?
    Thank you very much !

**Comment by SuperBruceJia** [comment]
+1

**Comment by 2279209430** [comment]
@vztu Thakns for your sharing !
